### ISSUE TITLE
Marbles do not authenticate Coordinator

### ISSUE THREAD

**Issue by gajjarvini** [edgelesssys/marblerun#168]
Hi Team,
From this [LINE](https://github.com/edgelesssys/marblerun/blob/8c39dc422794232295b273544d12d48198e00d41/util/tls.go#L116) 
I can understand that the "premain" logic of the Marbles do not authenticate the coordinator.
Could you please explain why a marble does not need to authenticate/verify coordinator's identity.

As coordinator manages the cryptographic keys of the marbles, is it not crucial for the marbles to authenticate a coordinator in order to trust it.

Please correct me if my understanding is wrong.

**Comment by m1ghtym0** [comment]
Hi @gajjarvini,
Your observation is correct.
The reasoning why the Marble does not need to authenticate the Coordinator is the following:

Assume that you have established a confidential service mesh with Coordinator `C` and a Marble `A` containing sensible data.
Assume that a Marble `B` wants to join the mesh but is redirected by an attacker to a malicious Coordinator `C*`.
It will receive parameters and credentials controlled by `C*`.
Since `C*` controls the bootstrapping of `B`, it has potentially arbitrary code execution in `B`.

Now consider the following scenarios:

* `A` wants to share data with `B`:
  * When `A` connects to `B` (or the other way around) `B` presents its certificate signed by `C*`.
  * `A` only trusts certificates signed by `C`, hence, the connection fails.
  * No data is shared. Essentially `B` did not join the service mesh of `C`. 
* A user `U` connects to service `B`.
  *  `U` verified the Coordinator `C` and received its root certificate (redirecting `U` to `C*` would lead to a failed verification)
  * `U` connects to `B` and is presented  with its certificate signed by `C*`
  *  `A` only trusts certificates signed by `C`, hence, the connection fails.

In summary,  during the "premain" logic, the Coordinator is the confidential part and the Marble is the untrusted part.
You could attack the Marble from a malicious Coordinator, but there is nothing to be gained there.
The Marble is not part of the mesh at that point. So such Marble is completely untrusted.

One might say that there is no harm in also verifying the Coordinator from the Marble as well.
The problem is that you would need some kind of ground truth on the Marble-side to verify the Coordinator, it's not straightforward to have this without compromises.

**Comment by m1ghtym0** [comment]
Yes, sorry, I'll edit my post.
