### ISSUE TITLE
[Coordinator] Go failure on Coordinator's Core startup `cipher: message authentication failed`

### ISSUE THREAD

**Issue by dimakuv** [edgelesssys/marblerun#217]
### Issue description

Followed the BUILD guide on the latest master of Marblerun, built the Coordinator successfully and tried to run via `erthost build/coordinator-enclave.signed`. Got the following error:
```
dimakuv@mehlow-prequal01:~/marblerun$ erthost build/coordinator-enclave.signed
[erthost] loading enclave ...
[erthost] entering enclave ...
[meshentry] invoking premain
[meshentry] invoking main
{"level":"info","ts":1626762646.9601912,"caller":"coordinator/run.go:49","msg":"starting coordinator","version":"0.4.0","commit":"3780c0eae950fdac9255018a8e328f9f90f7ea2b"}
{"level":"info","ts":1626762646.9601912,"caller":"coordinator/run.go:78","msg":"creating the Core object"}
{"level":"info","ts":1626762646.9601912,"caller":"core/core.go:132","msg":"loading state"}
{"level":"info","ts":1626762646.9601912,"caller":"core/core.go:170","msg":"No sealed state found. Proceeding with new state."}
panic: cipher: message authentication failed

goroutine 17 [running, locked to thread]:
main.run(0x7fed41571ef8, 0x7fed41b71770, 0x7fed41571ed8, 0x7fed41b71770, 0x7fed582880c0, 0x3d, 0x7fed415843e0, 0x7fed58236cc0, 0x7fed4158d098, 0x7fed5800f170)
        /home/dimakuv/marblerun/cmd/coordinator/run.go:84 +0x1105
main.main()
        /home/dimakuv/marblerun/cmd/coordinator/enclavemain.go:29 +0x23c
main.invokemain(...)
        /home/dimakuv/marblerun/cmd/coordinator/invokemain.go:15
```

Manual inspection of `/home/dimakuv/marblerun/cmd/coordinator/run.go:84` didn't give me clues. Apparently, `core.NewCore()` fails because some `message authentication failed`, though I don't know what this could mean.

WhenI removed the previous version completely (`rm marblerun`) and git-cloned and built again, the Marblerun Coordinator started successfully. So apparently I got some mismatch in versions of files -- I suspect the `marblerun-coordinator-data/sealed_key` file.

### To reproduce

This one is hard to reproduce because I had an old Marblerun version (git-cloned and built a couple months ago), and then I did `git pull` and rebuilt Marblerun. So it looks like there was some state left over from the old Marblerun version. However notice that I removed `marblerun-coordinator-data/sealed_data` file before starting the new Marblerun (bit did *not* remove `marblerun-coordinator-data/sealed_key` -- could that be the reason for a failure?).

### Expected behavior

Marblerun Coordinator should start without failures.

### Environment:
 - Marblerun version: latest master, commit 3780c0eae950fdac9255018a8e328f9f90f7ea2b
 - Edgeless RT version: v0.2.5
 - Go version: go version go1.16.3 linux/amd64
 - Minikube version: N/A

### Additional info / screenshots

Feel free to close it since on the clean build, it works. Just wanted to document this issue, for posterity. And also curious what exactly breaks.

**Comment by m1ghtym0** [comment]
Hi @dimakuv,

Yes, the problem is that you've deleted `marblerun-coordinator-data/sealed_data` but not `marblerun-coordinator-data/sealed_key`.
Because `sealed_data` doesn't exist the Coordinator does assume there is no sealed state on the disk: `"No sealed state found. Proceeding with new state."`.
Hence, it doesn't notice that it can't decrypt the key used for sealing (`sealed_key`) and does not go into recovery mode.
When it tries to seal the new state to disk however, it finds the `sealed_key` on the disk and tries to decrypt it.
Unfortunately, there we don't catch an error here because we assume we can decrypt this key, since we are not in recovery mode.
We should fix this problem by removing any `sealed_key` if no `sealed_state` is found on the disk when initializing the Coordinator.

**Comment by Nirusu** [comment]
Small note: "message authentication failed" is an error message from Go's when it fails to validate AES-GCM tags during decryption. Usually happens when a wrong key is used (which likely happens due to what @m1ghtym0 explained), causing Go to decrypt rubbish data which it cannot validate, hence throwing the error.

But yeah, not very intuitive to the user. We will improve this, thanks for the report :)

**Comment by dimakuv** [comment]
Thanks @m1ghtym0, that makes perfect sense. Feel free to close the issue.
