### ISSUE TITLE
How marble code inject premain before application start

### ISSUE THREAD

**Issue by Glenrun** [edgelesssys/marblerun#296]
### Use case

Some of my customer have some interest on marblerun, however i have to provide some detail on how marblerun and marble are implemented in detail, I'm not farmiliar at golang, can you provide some documentation or details on how marble inject some premain source code before application main?

**Comment by daniel-weisse** [comment]
Hi @Glenrun 

The marble premain is essentially a small program running before your actual application.
It's purpose is to attest itself to the Coordinator and receive its configuration as specified in MarbleRun's manifest.

The actual implementation differs slightly depending on how you built your marble.

#### Marble built using [Gramine](https://github.com/gramineproject/gramine) or [Occlum](https://github.com/occlum/occlum)
In this case the premain is an actual executable you include in the progress of building your Occlum/Gramine application.
When started, Gramine/Occlum execute the premain binary instead of your actual application.
The premain then attest itself to the MarbleRun coordinator, receives its configuraiton, and generates files, sets environment variables and sets `argv` according to the configuration.

Once this is done the actual application is started using [`execve`](https://man7.org/linux/man-pages/man2/execve.2.html).

Source code can be found here: https://github.com/edgelesssys/marblerun/tree/v0.5.1/cmd/premain-libos

#### Marble built using [EGo](https://github.com/edgelesssys/ego)
With EGo, the marble premain is part of the EGo CLI.
You take any binary built and signed with EGo and execute it with `ego marblerun <executable>`.
Here the marble premain is part of the EGo enclave setup code (which incidental is also called [`PreMain`](https://github.com/edgelesssys/ego/blob/55bad14bb8d00dbae2000a8d603f9b588bb79451/ego/premain/core/core.go#L50)).
During this setup code we check if the program is supposed to be running as a marble, and if yes, run the marble premain.

Source code can be found here: https://github.com/edgelesssys/ego/tree/v0.5.0/ego/premain

**Comment by Glenrun** [comment]
> 

@daniel-weisse Thanks for quick reply. I can understand the way marble built using libos, but not for built using EGo. Take the `marblerun/samples/helloworld/hello.go` for example, you know there is `func main()` which contains the application logic in hello.go, and I can get  `ert_ego_premain` invokes core package's `PreMain`,  then it invokes marble's `PreMainEgo`  what I'm not sure is how `ert_ego_premain` from `ego/premain/main.go` gets invoked before the `func main`? Who does the magic behind and how?

**Comment by thomasten** [comment]
An EGo enclave consists of two parts:
* the EGo runtime called ego-enclave, which, among other things, contains the enclave entrypoint and also the premain code
* and the actual payload compiled with ego-go.

Here's some code from ego-enclave:
https://github.com/edgelesssys/ego/blob/19fe24700941af32c196bce44ded7afc3e54f87f/src/enc.cpp#L132-L175
You can see the call to ert_ego_premain in line 133 and the call to the payload's entrypoint in line 175.

**Comment by Glenrun** [comment]
@thomasten Got it. Thanks for clarification! It seems edgelessdb uses a different way to start mysql, could you kindly provide any detail on edgelessdb?

**Comment by thomasten** [comment]
Regarding EdgelessDB, MariaDB is statically linked to the rest of the enclave. After the manifest has been set, mysqld_main is called to start it.

**Comment by m1ghtym0** [comment]
Since this is stale for a while now and all questions got answered I'm closing this issue.
