### ISSUE TITLE
Add -allow-tcb-status to coordinator manifest

### ISSUE THREAD

**Issue by henrysun007** [edgelesssys/marblerun#374]
### Use case

I am using marblerun on my local machine whose TCB is out-of-date. The coordinator failed to activate the marble. The log is listed  below:
```
caller":"core/marbleapi.go:81","msg":"Marble verification failed","error":"invalid quote: verifying quote failed: OE_TCB_LEVEL_INVALID"}
```

### Describe your solution

I found that someone else encounted the problem before. Why not allow the TCB error according to coordinator manifest?

**Comment by daniel-weisse** [comment]
Hi @henrysun007 

Setting allowed TCB statuses should be available since release v1.0.
See the changes in this PR: https://github.com/edgelesssys/marblerun/pull/344

On the CLI side you can verify a coordinator running on a machine whose TCB is out-of-date using the `--accepted-tcb-statuses` flag.
For allowing marble on machines whose TCB is out-of-date, you can set the `AcceptedTCBStatuses` key of a package to the values you deem acceptable.

Though the actual feature is already available, it seems like the second part is not yet reflected in our docs. I will update them as soon as possible.
