### ISSUE TITLE
Question regarding MITM on Deployment

### ISSUE THREAD

**Issue by paulgoehring** [edgelesssys/marblerun#518]
Hello,
During my research on Marblerun I came to the question how exactly a MITM Attack is prevented during the Deployment Phase? If I understand the Code correctly the communication flow is like this:

1) Marble initializes Enclave and computes Hash value
2) Marble generates own TLS Certificate
3) Marble registers with self signed Certificate and Enclave Hash at Coordinator but does not verify the Coordinator
4) Coordinator verifies Hash and creates Key Pair and corresponding x.509 Certificate
5) Coordinator sends X.509 Certificate and Key Pair

So now to my Question: 
Since the Coordinator does not know anything about the self created Key Pair + TLS Certificate by the Marble it can not be part of the Hash of the Measurement, because it would change it so that the coordinator can not verify the marble anymore. Why can't there be a Man in the middle just switching the marbles TLS Certificate with his own and forward the expected measurement to the Coordinator? That way the coordinator would now send him a valid Key Pair + Certificate and he could impersonate the Marble. Is this self created TLS Certificate send additionally somewhere in the Quote and therefore the Connection can get verified? I could not find this in the Code but it would make sense to me. 
And if so what is the reason the Coordinator creates an additional Key Pair for the X.509 Certificate and does not use the Key Pair created by the Marble? Is it not a unnecessary risk to have all private Keys in one place and send them over the network even if it is inside an Enclave and over a MTLS connection?

I am sure i am missing something but I want to use Marblerun in my Thesis regarding Confidential Computing in the Cloud and therefore i should be able to explain every step of the way.

Thanks in advance

**Comment by thomasten** [comment]
Hi Paul,
Thanks for looking into MarbleRun!
Your understanding of the communication flow is correct.

> Is this self created TLS Certificate send additionally somewhere in the Quote and therefore the Connection can get verified?

Yes, that's exactly how it works. The quote contains a `report_data` field, which we use to include the certificate's hash:

https://github.com/edgelesssys/marblerun/blob/411e3bcbb01a9a069c69d87f6713a0cde282511b/marble/premain/premain.go#L170
https://github.com/edgelesssys/marblerun/blob/411e3bcbb01a9a069c69d87f6713a0cde282511b/coordinator/quote/ertvalidator/ertvalidator.go#L45-L49

> what is the reason the Coordinator creates an additional Key Pair for the X.509 Certificate and does not use the Key Pair created by the Marble? Is it not a unnecessary risk to have all private Keys in one place and send them over the network even if it is inside an Enclave and over a MTLS connection?

As a user, you can [define Parameters in the manifest](https://docs.edgeless.systems/marblerun/workflows/define-manifest#marbles) for a Marble. On Marble activation, the Coordinator generates these parameters and sends them to the Marble. One feature is to inject the private key into the parameters. That's why the Coordinator creates the key pair.

Hope that helps.

**Comment by paulgoehring** [comment]
Thanks a lot for the quick response and the relevant parts of the code, this was really helpful. 

I still have one follow up question. As far as i see it first all the Attestation gets done and if it is verified successful then the Coordinator takes the CSR and creates the X.509 Certificate with the Key Pair created by the Coordinator. Would it not be more secure if we just take the Public Key of the CSR and create our X.509 Certificate with this Key since the corresponding private Key is already on the marble and just the marble knows its value? Is this not possible to inject this Key from our Premain into our Application?
At first I thought the reason for the Key Injection is that the Coordinator knows the expected Hash and therefore it could become part of the Quote. Then we could verify that this key is part of the application and so we would have an attested key in our application. But it does not seem to work like that and I am not sure if it even would be possible.

**Comment by paulgoehring** [comment]
Sorry

**Comment by thomasten** [comment]
Yes, you're right, technically, it would be possible to inject that key within the Premain. However, the Coordinator also manages other secrets for the Marble that needs to be injected. That's why we decided to keep the injection logic at one place.

Regarding security, this is a tradeoff between limiting the places where the key is processed vs keeping the TCB of the Marble/Premain small. As you already said, in theory both is okay because of enclaves and MTLS.

**Comment by dimakuv** [comment]
> Would it not be more secure if we just take the Public Key of the CSR and create our X.509 Certificate with this Key since the corresponding private Key is already on the marble and just the marble knows its value? Is this not possible to inject this Key from our Premain into our Application?

That's exactly the question I had when looking at https://docs.edgeless.systems/marblerun/architecture/security#public-key-infrastructure-and-certificate-authority.

> Yes, you're right, technically, it would be possible to inject that key within the Premain. However, the Coordinator also manages other secrets for the Marble that needs to be injected. That's why we decided to keep the injection logic at one place.

> Regarding security, this is a tradeoff between limiting the places where the key is processed vs keeping the TCB of the Marble/Premain small. As you already said, in theory both is okay because of enclaves and MTLS.

Thanks for these explanations! The argument of "keeping all the logic in one place" makes perfect sense to me.
